# Generated by Django 5.1.6 on 2025-03-07 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0002_rename_total_due_pio_buyer_due_pio_seller_due_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_payable',
        ),
    ]
