# Generated by Django 5.1.6 on 2025-03-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0003_remove_customer_total_payable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pio',
            name='pio_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
