# Generated by Django 5.1.6 on 2025-03-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0004_alter_pio_unique_together_alter_pio_pio_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pio',
            name='pio_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='pio',
            unique_together={('customer', 'pio_number')},
        ),
    ]
