# Generated by Django 5.1.6 on 2025-03-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0005_alter_pio_pio_number_alter_pio_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pio',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pio',
            name='pio_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
