# Generated by Django 5.1.6 on 2025-03-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0006_alter_pio_unique_together_alter_pio_pio_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pio',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
