# Generated by Django 5.1.6 on 2025-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0007_pio_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pio',
            name='total_paid_pio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
