# Generated by Django 5.1.6 on 2025-03-14 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0008_pio_total_paid_pio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pio',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
