# Generated by Django 5.1.6 on 2025-03-22 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenseApp', '0002_expense_created_at_expense_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at']},
        ),
    ]
