# Generated by Django 5.1.6 on 2025-03-10 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsApp', '0002_product_created_at_product_updated_at'),
        ('purchaseApp', '0002_alter_purchase_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsApp.product'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='purchaseApp.purchase'),
        ),
    ]
