# Generated by Django 5.1.6 on 2025-03-10 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0007_pio_total_amount'),
        ('purchaseApp', '0003_alter_purchaseitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='customerApp.customer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='pio_number',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customerApp.pio'),
        ),
    ]
