# Generated by Django 5.1.6 on 2025-03-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseApp', '0004_alter_purchase_customer_alter_purchase_pio_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-created_at']},
        ),
    ]
