# Generated by Django 5.1.6 on 2025-03-14 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerApp', '0007_pio_total_amount'),
        ('purchaseApp', '0006_alter_purchase_pio_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='pio_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='customerApp.pio'),
        ),
    ]
