# Generated by Django 5.1.6 on 2025-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
